version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_non_tags: true
max_jobs: 1
image: Visual Studio 2017
configuration: ReleasePortable
platform:
- x64
- x86
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: normal
test: off
artifacts:
- path: Build/**/ModMonitor*.zip
  name: Package